plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 4.0
  DisplayCopNames: true
  NewCops: enable # but feel free to disable them below
  SuggestExtensions: false
  Exclude:
      - vendor/**/*
      - config.ru

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Max: 125

Metrics:
  Enabled: false

RSpec/ClassCheck:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/PendingWithoutReason:
   Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/ModuleFunction:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 15

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    "%": ()
    "%i": ()
    "%q": ()
    "%Q": ()
    "%r": "{}"
    "%s": ()
    "%w": ()
    "%W": ()
    "%x": ()

# Configuration parameters: AllowAsExpressionSeparator.
Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolProc:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  EnforcedStyle: percent

Style/SignalException:
  EnforcedStyle: semantic
